# Generated by Django 6.0.2 on 2026-03-02 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('credit', models.FloatField(default=3.0)),
                ('semester', models.CharField(choices=[('1-1', '1st Year - Sem 1'), ('1-2', '1st Year - Sem 2'), ('2-1', '2nd Year - Sem 1'), ('2-2', '2nd Year - Sem 2'), ('3-1', '3rd Year - Sem 1'), ('3-2', '3rd Year - Sem 2'), ('4-1', '4th Year - Sem 1'), ('4-2', '4th Year - Sem 2')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('batch', models.CharField(choices=[('Batch-51', 'Batch 51'), ('Batch-52', 'Batch 52'), ('Batch-53', 'Batch 53'), ('Batch-54', 'Batch 54')], max_length=20, verbose_name='Batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_point', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='predictor.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1-1', '1st Year - Sem 1'), ('1-2', '1st Year - Sem 2'), ('2-1', '2nd Year - Sem 1'), ('2-2', '2nd Year - Sem 2'), ('3-1', '3rd Year - Sem 1'), ('3-2', '3rd Year - Sem 2'), ('4-1', '4th Year - Sem 1'), ('4-2', '4th Year - Sem 2')], max_length=5)),
                ('attendance', models.FloatField(help_text='Attendance %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assignment', models.FloatField(default=0.0, help_text='Avg Assignment Marks')),
                ('quiz', models.FloatField(default=0.0, help_text='Avg Quiz Marks')),
                ('midterm', models.FloatField(default=0.0, help_text='Avg Midterm Marks')),
                ('final', models.FloatField(default=0.0, help_text='Avg Final Marks')),
                ('gpa', models.FloatField(help_text='Semester GPA', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_records', to='predictor.student')),
            ],
            options={
                'ordering': ['student', 'semester'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
