# Generated by Django 6.0.2 on 2026-02-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('attendance', models.FloatField(help_text='Attendance % (e.g. 85)')),
                ('assignment', models.FloatField(help_text='Assignment Score')),
                ('quiz', models.FloatField(help_text='Quiz Score')),
                ('midterm', models.FloatField(help_text='Midterm Score')),
                ('final', models.FloatField(help_text='Final Score')),
                ('gpa', models.FloatField(help_text='GPA obtained in this semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.student')),
            ],
        ),
    ]
