# Generated by Django 6.0.2 on 2026-03-02 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectscore',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='studentsubjectscore',
            name='grade',
            field=models.CharField(blank=True, help_text='Letter Grade (A+, B, etc.)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentsubjectscore',
            name='marks',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('1-1', '1st Year - Sem 1'), ('1-2', '1st Year - Sem 2'), ('2-1', '2nd Year - Sem 1'), ('2-2', '2nd Year - Sem 2'), ('3-1', '3rd Year - Sem 1'), ('3-2', '3rd Year - Sem 2'), ('4-1', '4th Year - Sem 1'), ('4-2', '4th Year - Sem 2')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubjectscore',
            name='grade_point',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
