# Generated by Django 6.0.2 on 2026-02-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicrecord',
            options={'ordering': ['semester']},
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='assignment',
            field=models.FloatField(default=0.0, help_text='Assignment Marks (0-100)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='attendance',
            field=models.FloatField(default=0.0, help_text='Attendance % (0-100)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='final',
            field=models.FloatField(default=0.0, help_text='Final Exam Marks (0-100)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='gpa',
            field=models.FloatField(default=0.0, help_text='GPA (0.00 - 4.00)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='midterm',
            field=models.FloatField(default=0.0, help_text='Midterm Marks (0-100)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='quiz',
            field=models.FloatField(default=0.0, help_text='Quiz Marks (0-100)'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='semester',
            field=models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], max_length=5, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='predictor.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'semester')},
        ),
    ]
