# Generated by Django 6.0.2 on 2026-03-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_remove_studentsubjectscore_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='assignment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='attendance',
            field=models.FloatField(help_text='Attendance percentage'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='midterm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='quiz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='semester',
            field=models.CharField(choices=[('1-1', '1st Year - Sem 1'), ('1-2', '1st Year - Sem 2'), ('2-1', '2nd Year - Sem 1'), ('2-2', '2nd Year - Sem 2'), ('3-1', '3rd Year - Sem 1'), ('3-2', '3rd Year - Sem 2'), ('4-1', '4th Year - Sem 1'), ('4-2', '4th Year - Sem 2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.student'),
        ),
    ]
