# Generated by Django 6.0.2 on 2026-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_academicrecord_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrecord',
            name='midterm',
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='attendance',
            field=models.FloatField(help_text='Attendance percentage (0-100)'),
        ),
    ]
