# Generated by Django 6.0.2 on 2026-02-28 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_subjectperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('1-1', '1st Year - Sem 1'), ('1-2', '1st Year - Sem 2'), ('2-1', '2nd Year - Sem 1'), ('2-2', '2nd Year - Sem 2'), ('3-1', '3rd Year - Sem 1'), ('3-2', '3rd Year - Sem 2'), ('4-1', '4th Year - Sem 1'), ('4-2', '4th Year - Sem 2')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.student')),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectPerformance',
        ),
    ]
